### ISSUE TITLE
Behaviour of {select} integration helper, only works with `on-change`?

### ISSUE THREAD

**Issue by corrspt** [adopted-ember-addons/emberx-select#225]
### Version of x-select:
3.1.1
### Ember Version / Ember CLI Version:

**Ember Version:**
3.2.2
**Ember CLI Version:**
3.2.0
### Expected Behavior
Hi,

I'm having an issue with the `select` integration helper. I've created a component that uses `ember-xselect` with a definition like the following:

```
{{#x-select
        value=this.diameter1
        on-click=action 'updateDiameter1')
        one-way=true
        as |xs|}}
        ... (options)
    {{/x-select}}
```
And this works, fine. But I've I tried adding a test that uses the ` { select ` } helper and it didn't work. Only when I changed to an `on-change` handler it started working, but looking at the code for the select helper, it does have a "trigger('change') (https://github.com/thefrontside/emberx-select/blob/master/test-support/helpers/x-select.js#L31)

### Steps To Reproduce:
1. Create component that uses ember-xselect with an `on-click` handler
2. Create a test that uses the `{ select }` helper
3. Run the test to assert something that required the select to select something

### Ember Twiddle / Example repo / Failing test:
I don't know how to create a Twiddle, as I don't know how to make this step from the the readme in Twiddle:
`import { select } from '_MY_APP_/tests/helpers/x-select';` (Don't know what "MY_APP" name is on Twiddle)

**Comment by Robdel12** [comment]
Hey @corrspt, thanks for bringing this up! Yea, the 3.x test helper doesn't do anything other than trigger change (when selecting). You can manually trigger a click on the element within your tests to achieve this (or use the ember click helper).

In x-select 4.x you'll be able to do `xselect.click()` (as well as `xselect.select('option') or xselect.focus()`: 

[You can read more about the new helper that's coming here](https://github.com/thefrontside/emberx-select#test-helper) 😃

**Comment by corrspt** [comment]
Hi @Robdel12 

Got it, thanks for letting me know :) I'll be waiting for version 4, then :) 

Should I close the issue?

**Comment by corrspt** [comment]
I'm closing the issue. I've updated to the latest beta and my life is easier. Thanks for the v4-beta  @Robdel12 :)
